openapi: 3.0.1
info:
  title: Add Sentinel Incident Comment API
  version: 1.0.0

servers:
  - url: https://management.azure.com

paths:
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/incidents/{incidentId}/comments/{commentId}:
    put:
      summary: Add or update a comment on a Sentinel incident
      operationId: AddSentinelIncidentComment

      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema: { type: string }
        - name: resourceGroup
          in: path
          required: true
          schema: { type: string }
        - name: workspaceName
          in: path
          required: true
          schema: { type: string }
        - name: incidentId
          in: path
          required: true
          schema: { type: string }
        - name: commentId
          in: path
          required: true
          description: GUID for the comment resource
          schema: { type: string }
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            enum:
              - "2025-07-01-preview"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  type: object
                  properties:
                    message:
                      type: string
                      description: Comment text
                  required:
                    - message
              required:
                - properties
              x-ms-requestBody-name: requestBody

      responses:
        "200": { description: Comment updated }
        "201": { description: Comment created }
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "403": { description: Forbidden }
        "404": { description: Not Found }
        "500": { description: Internal Server Error }

      security:
        - azure_auth:
            - https://management.azure.com/.default

components:
  securitySchemes:
    azure_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
          scopes:
            https://management.azure.com/.default: Access ARM API
